name: Periodic Health Check

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  check_health:
    runs-on: ubuntu-latest

    steps:
      - name: Check health endpoint
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://pokedex-5s4h.onrender.com/health'


          #made changes to the url to point to the correct health endpoint